### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by clement911** [snowplow/referer-parser#146]
Is this project still being maintained?
I can see that there are many open pull requests and no commits for a while...

**Comment by ispringer** [comment]
And the last release of the Java-Scala version was almost 2 years ago.

**Comment by danm** [comment]
@clement911 @ispringer what did you guys do instead? does a replacement exist? I have been using Piwik instead but if there was a better community dataset we would be able to maintain?

**Comment by alexanderdean** [comment]
Hi all - apologies for the delay - we are bringing this project up-to-date after a long hiatus.

We are happy to do a monthly release of the referers database, similar to how Maxmind do their release process.

In terms of the libraries/SDKs, what needs to happen is:

1. Move each library into its own repo, per #140
2. Update each library so that it uses the standalone database, rather than an embedded data file (which obviously ages with the SDK)
